{{- if .Values.externalSecrets.enabled }}
{{- if .Values.externalSecrets.secretStore.create }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
  labels:
    {{- include "atlas-rag.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.secretStore.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "atlas-rag.serviceAccountName" . }}
---
{{- end }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "atlas-rag.fullname" . }}
  labels:
    {{- include "atlas-rag.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.externalSecrets.secretStore.name }}
  target:
    name: {{ .Values.existingSecret }}
    creationPolicy: Owner
    deletionPolicy: Retain
    {{- with .Values.externalSecrets.targetTemplate }}
    template:
      engineVersion: v2
      data:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  data:
    {{- range .Values.externalSecrets.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey | quote }}
        {{- with .property }}
        property: {{ . | quote }}
        {{- end }}
    {{- end }}
{{- end }}
